/**
 * Text Style Presets for FlareLab Text Studio
 * Broadcast-quality text styles for sports graphics
 */

import type { TextStylePreset } from '../../types/project.types';

export const TEXT_STYLE_PRESETS: TextStylePreset[] = [
  // ===== ICE / FROZEN STYLES =====
  {
    id: 'frozen-ice',
    name: 'Frozen Ice',
    category: 'ice',
    description: 'Icy blue gradient with frost glow effect',
    keywords: ['ice', 'frozen', 'cold', 'winter', 'frost', 'arctic', 'avalanche', 'snow', 'blue', 'chill'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 72,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#ffffff' },
          { offset: 0.3, color: '#a5f3fc' },
          { offset: 0.7, color: '#22d3ee' },
          { offset: 1, color: '#0891b2' },
        ],
      },
      strokeColor: '#164e63',
      strokeWidth: 3,
      shadowColor: 'rgba(34, 211, 238, 0.8)',
      shadowBlur: 15,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#22d3ee',
      glowBlur: 25,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'FROZEN',
  },
  {
    id: 'arctic-blast',
    name: 'Arctic Blast',
    category: 'ice',
    description: 'Deep blue ice with white highlights',
    keywords: ['arctic', 'blast', 'ice', 'cold', 'freeze', 'blizzard', 'polar', 'glacier'],
    style: {
      fontFamily: 'Oswald',
      fontSize: 68,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#e0f2fe' },
          { offset: 0.5, color: '#7dd3fc' },
          { offset: 1, color: '#0369a1' },
        ],
      },
      strokeColor: '#082f49',
      strokeWidth: 4,
      shadowColor: 'rgba(125, 211, 252, 0.6)',
      shadowBlur: 20,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      textTransform: 'uppercase',
      letterSpacing: 6,
    },
    previewText: 'ARCTIC',
  },

  // ===== FIRE / INTENSITY STYLES =====
  {
    id: 'fire-intensity',
    name: 'Fire Intensity',
    category: 'fire',
    description: 'Blazing orange to red gradient with ember glow',
    keywords: ['fire', 'intensity', 'heat', 'blaze', 'flame', 'hot', 'burn', 'ember', 'inferno', 'passion'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 72,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#fef08a' },
          { offset: 0.3, color: '#fb923c' },
          { offset: 0.7, color: '#ea580c' },
          { offset: 1, color: '#9a3412' },
        ],
      },
      strokeColor: '#7c2d12',
      strokeWidth: 3,
      shadowColor: 'rgba(251, 146, 60, 0.8)',
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#f97316',
      glowBlur: 30,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'BLAZE',
  },
  {
    id: 'inferno',
    name: 'Inferno',
    category: 'fire',
    description: 'Deep red flames with yellow core',
    keywords: ['inferno', 'hell', 'fire', 'flames', 'red', 'danger', 'explosive', 'volcanic'],
    style: {
      fontFamily: 'Anton',
      fontSize: 70,
      fontWeight: 400,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#fde047' },
          { offset: 0.4, color: '#ef4444' },
          { offset: 1, color: '#7f1d1d' },
        ],
      },
      strokeColor: '#450a0a',
      strokeWidth: 4,
      shadowColor: 'rgba(239, 68, 68, 0.7)',
      shadowBlur: 25,
      shadowOffsetX: 0,
      shadowOffsetY: 5,
      textTransform: 'uppercase',
      letterSpacing: 3,
    },
    previewText: 'INFERNO',
  },

  // ===== METALLIC / GOLD STYLES =====
  {
    id: 'metallic-gold',
    name: 'Metallic Gold',
    category: 'metallic',
    description: 'Luxurious gold gradient with shine',
    keywords: ['gold', 'metallic', 'luxury', 'champion', 'winner', 'trophy', 'premium', 'rich'],
    style: {
      fontFamily: 'Oswald',
      fontSize: 68,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 135,
        stops: [
          { offset: 0, color: '#fef9c3' },
          { offset: 0.25, color: '#fcd34d' },
          { offset: 0.5, color: '#f59e0b' },
          { offset: 0.75, color: '#d97706' },
          { offset: 1, color: '#92400e' },
        ],
      },
      strokeColor: '#78350f',
      strokeWidth: 2,
      shadowColor: 'rgba(245, 158, 11, 0.5)',
      shadowBlur: 15,
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      textTransform: 'uppercase',
      letterSpacing: 5,
    },
    previewText: 'GOLD',
  },
  {
    id: 'chrome-steel',
    name: 'Chrome Steel',
    category: 'metallic',
    description: 'Polished chrome with reflective highlights',
    keywords: ['chrome', 'steel', 'metal', 'silver', 'industrial', 'modern', 'sleek', 'tech'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 72,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#f8fafc' },
          { offset: 0.3, color: '#cbd5e1' },
          { offset: 0.5, color: '#94a3b8' },
          { offset: 0.7, color: '#64748b' },
          { offset: 1, color: '#334155' },
        ],
      },
      strokeColor: '#1e293b',
      strokeWidth: 3,
      shadowColor: 'rgba(148, 163, 184, 0.6)',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'CHROME',
  },
  {
    id: 'bronze-glory',
    name: 'Bronze Glory',
    category: 'metallic',
    description: 'Warm bronze with antique finish',
    keywords: ['bronze', 'glory', 'antique', 'classic', 'third', 'medal', 'heritage'],
    style: {
      fontFamily: 'Anton',
      fontSize: 68,
      fontWeight: 400,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 160,
        stops: [
          { offset: 0, color: '#fef3c7' },
          { offset: 0.4, color: '#d97706' },
          { offset: 0.7, color: '#a16207' },
          { offset: 1, color: '#713f12' },
        ],
      },
      strokeColor: '#422006',
      strokeWidth: 3,
      shadowColor: 'rgba(161, 98, 7, 0.5)',
      shadowBlur: 12,
      shadowOffsetX: 2,
      shadowOffsetY: 3,
      textTransform: 'uppercase',
      letterSpacing: 3,
    },
    previewText: 'BRONZE',
  },

  // ===== NEON / ELECTRIC STYLES =====
  {
    id: 'neon-electric',
    name: 'Neon Electric',
    category: 'neon',
    description: 'Bright neon pink with electric glow',
    keywords: ['neon', 'electric', 'glow', 'night', 'vibrant', 'retro', '80s', 'synthwave', 'pink'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 72,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#f0abfc',
      strokeColor: '#a855f7',
      strokeWidth: 2,
      shadowColor: 'rgba(217, 70, 239, 0.9)',
      shadowBlur: 30,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#d946ef',
      glowBlur: 40,
      textTransform: 'uppercase',
      letterSpacing: 6,
    },
    previewText: 'NEON',
  },
  {
    id: 'cyber-blue',
    name: 'Cyber Blue',
    category: 'neon',
    description: 'Electric blue cyberpunk style',
    keywords: ['cyber', 'blue', 'futuristic', 'tech', 'digital', 'neon', 'cyberpunk', 'sci-fi'],
    style: {
      fontFamily: 'Orbitron',
      fontSize: 64,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#7dd3fc',
      strokeColor: '#0284c7',
      strokeWidth: 2,
      shadowColor: 'rgba(56, 189, 248, 0.9)',
      shadowBlur: 35,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#38bdf8',
      glowBlur: 45,
      textTransform: 'uppercase',
      letterSpacing: 8,
    },
    previewText: 'CYBER',
  },
  {
    id: 'toxic-green',
    name: 'Toxic Green',
    category: 'neon',
    description: 'Radioactive green neon glow',
    keywords: ['toxic', 'green', 'radioactive', 'neon', 'acid', 'poison', 'energy', 'power'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 70,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#86efac',
      strokeColor: '#16a34a',
      strokeWidth: 2,
      shadowColor: 'rgba(74, 222, 128, 0.9)',
      shadowBlur: 30,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#4ade80',
      glowBlur: 40,
      textTransform: 'uppercase',
      letterSpacing: 5,
    },
    previewText: 'TOXIC',
  },

  // ===== BROADCAST / CLEAN STYLES =====
  {
    id: 'broadcast-clean',
    name: 'Broadcast Clean',
    category: 'broadcast',
    description: 'Professional broadcast-ready white text',
    keywords: ['broadcast', 'clean', 'professional', 'tv', 'news', 'sports', 'white', 'standard'],
    style: {
      fontFamily: 'Oswald',
      fontSize: 64,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#ffffff',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 0, 0, 0.7)',
      shadowBlur: 8,
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      textTransform: 'uppercase',
      letterSpacing: 3,
    },
    previewText: 'BROADCAST',
  },
  {
    id: 'sports-bold',
    name: 'Sports Bold',
    category: 'broadcast',
    description: 'Bold athletic style with drop shadow',
    keywords: ['sports', 'bold', 'athletic', 'game', 'match', 'strong', 'powerful', 'impact'],
    style: {
      fontFamily: 'Anton',
      fontSize: 72,
      fontWeight: 400,
      fillType: 'solid',
      fillColor: '#ffffff',
      strokeColor: '#1f2937',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 0, 0, 0.8)',
      shadowBlur: 0,
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      textTransform: 'uppercase',
      letterSpacing: 2,
    },
    previewText: 'SPORTS',
  },
  {
    id: 'headline-impact',
    name: 'Headline Impact',
    category: 'broadcast',
    description: 'High-impact headline style',
    keywords: ['headline', 'impact', 'news', 'breaking', 'alert', 'announcement', 'big'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 80,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#fef9c3',
      strokeColor: '#1e293b',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 0,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'IMPACT',
  },

  // ===== TEAM-THEMED STYLES =====
  {
    id: 'team-primary',
    name: 'Team Primary',
    category: 'team',
    description: 'Customizable team color style',
    keywords: ['team', 'primary', 'color', 'brand', 'identity', 'home', 'jersey'],
    style: {
      fontFamily: 'Oswald',
      fontSize: 68,
      fontWeight: 700,
      fillType: 'solid',
      fillColor: '#f97316', // Default orange, customizable
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 0, 0, 0.7)',
      shadowBlur: 10,
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'TEAM',
  },
  {
    id: 'rivalry-clash',
    name: 'Rivalry Clash',
    category: 'team',
    description: 'Split color for rivalry matchups',
    keywords: ['rivalry', 'clash', 'versus', 'vs', 'battle', 'matchup', 'showdown', 'dual'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 72,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 90,
        stops: [
          { offset: 0, color: '#ef4444' },
          { offset: 0.45, color: '#ef4444' },
          { offset: 0.55, color: '#3b82f6' },
          { offset: 1, color: '#3b82f6' },
        ],
      },
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 0, 0, 0.8)',
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      textTransform: 'uppercase',
      letterSpacing: 5,
    },
    previewText: 'VS',
  },

  // ===== DRAMATIC / CINEMATIC STYLES =====
  {
    id: 'epic-cinematic',
    name: 'Epic Cinematic',
    category: 'dramatic',
    description: 'Movie poster style with dramatic shadow',
    keywords: ['epic', 'cinematic', 'movie', 'poster', 'dramatic', 'blockbuster', 'hollywood'],
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 76,
      fontWeight: 700,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#fafafa' },
          { offset: 0.5, color: '#d4d4d4' },
          { offset: 1, color: '#737373' },
        ],
      },
      strokeColor: '#171717',
      strokeWidth: 3,
      shadowColor: 'rgba(0, 0, 0, 0.95)',
      shadowBlur: 0,
      shadowOffsetX: 6,
      shadowOffsetY: 8,
      textTransform: 'uppercase',
      letterSpacing: 6,
    },
    previewText: 'EPIC',
  },
  {
    id: 'dark-knight',
    name: 'Dark Knight',
    category: 'dramatic',
    description: 'Dark moody style with subtle glow',
    keywords: ['dark', 'knight', 'moody', 'noir', 'shadow', 'mysterious', 'gothic', 'night'],
    style: {
      fontFamily: 'Anton',
      fontSize: 72,
      fontWeight: 400,
      fillType: 'gradient',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          { offset: 0, color: '#525252' },
          { offset: 0.5, color: '#262626' },
          { offset: 1, color: '#0a0a0a' },
        ],
      },
      strokeColor: '#404040',
      strokeWidth: 2,
      shadowColor: 'rgba(64, 64, 64, 0.5)',
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowColor: '#525252',
      glowBlur: 15,
      textTransform: 'uppercase',
      letterSpacing: 4,
    },
    previewText: 'DARK',
  },
];

// Helper function to get presets by category
export function getPresetsByCategory(category: string): TextStylePreset[] {
  return TEXT_STYLE_PRESETS.filter(preset => preset.category === category);
}

// Get all unique categories
export function getPresetCategories(): string[] {
  const categories = new Set(TEXT_STYLE_PRESETS.map(preset => preset.category));
  return Array.from(categories);
}

// Get preset by ID
export function getPresetById(id: string): TextStylePreset | undefined {
  return TEXT_STYLE_PRESETS.find(preset => preset.id === id);
}

// Category display names and colors
export const PRESET_CATEGORY_INFO: Record<string, { label: string; color: string }> = {
  ice: { label: 'Ice & Frozen', color: '#22d3ee' },
  fire: { label: 'Fire & Heat', color: '#f97316' },
  metallic: { label: 'Metallic', color: '#fcd34d' },
  neon: { label: 'Neon & Electric', color: '#d946ef' },
  broadcast: { label: 'Broadcast', color: '#94a3b8' },
  team: { label: 'Team Colors', color: '#22c55e' },
  dramatic: { label: 'Dramatic', color: '#a855f7' },
};
